name: "Python CI"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/python-ci.yml"
      - "pyproject.toml"
      - "uv.lock"
      - "**/*.py"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/python-ci.yml"
      - "pyproject.toml"
      - "uv.lock"
      - "**/*.py"

jobs:
  lint:
    name: "Lint & Typecheck"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: "Install dependencies"
        run: uv sync --locked

      - name: "Cache MyPy"
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            mypy-${{ runner.os }}-

      - name: "MyPy: Typecheck"
        run: uv run mypy .
    
      - name: "Ruff: Static Analysis"
        run: uv run ruff check .

      - name: "Ruff: Format Check"
        run: uv run ruff format --check .
